# Dockerfile.lazada
FROM mcr.microsoft.com/playwright/python:v1.42.0-jammy

# Set working directory
WORKDIR /app

# Copy necessary files
COPY lazada_svc.py .
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install Playwright browsers
RUN playwright install

# Expose FastAPI's port
EXPOSE 8001

# Run the service
CMD ["uvicorn", "lazada_svc:app", "--host", "0.0.0.0", "--port", "8001"]