# Dockerfile.carousell
FROM mcr.microsoft.com/playwright/python:v1.42.0-jammy

# Set working directory
WORKDIR /app

# Copy only necessary files
COPY carousell_svc.py .
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install Playwright browsers
RUN playwright install

# Expose the port used by FastAPI
EXPOSE 8002

# Start the FastAPI app using uvicorn
CMD ["uvicorn", "carousell_svc:app", "--host", "0.0.0.0", "--port", "8002"]